<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EldenDeathCounter.Core\EldenDeathCounter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\Assets\*.*" Link="Assets\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Icons\*.*" Link="Assets\Icons\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Elden Ring\*.*" Link="Assets\Elden Ring\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Elden Ring\Reforge\*.*" Link="Assets\Elden Ring\Reforge\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Elden Ring\Convergence\*.*" Link="Assets\Elden Ring\Convergence\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Dark souls 3\*.*" Link="Assets\Dark souls 3\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Dark souls 2\*.*" Link="Assets\Dark souls 2\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Black Myth Wukong\*.*" Link="Assets\Black Myth Wukong\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Assets\Sekiro\*.*" Link="Assets\Sekiro\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\Assets\Fonts\*.ttf" Link="Assets\Fonts\%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <SatelliteResourceLanguages>en;pl</SatelliteResourceLanguages>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\Assets\Icons\AppIcon.ico</ApplicationIcon>
    <Version>1.15.2</Version>
  </PropertyGroup>

</Project>
